[14.0][IMP] intrastat_*: Improve tests and code
OCA/intrastat-extrastat pull request #149
Opened 2021-10-23 16:49 UTC by rousseldenis

- [x] No breaking changes
- [x] Rewrite tests to help test extensions
- [x] Move common code. Some code was called in intrastat_base making reference to inexistent fields in Abstract (company_id, company_country_code, state, year, month).

2021-10-24 12:12 UTC, rousseldenis commented
I think this first one is ready.

I would say it deserves one more amount of work to increase coverage, but with this, I would tend to say you can extend it and test your modifications in as simpler way.

@luc-demeyer @alexis-via @OCA/accounting-maintainers

2021-11-09 20:05 UTC, luc-demeyer requested changes

2021-11-09 20:05 UTC, luc-demeyer commented on intrastat_product/tests/common.py
> +        cls._create_region()
In Belgium the instrastat regions are Flemish Region, Walloon Region, Brussels-Capital Region.
The region field should not be used for the country

2021-11-09 20:05 UTC, luc-demeyer commented on intrastat_product/tests/common.py
> +        if vals is not None:
In Belgium the instrastat regions are Flemish Region, Walloon Region, Brussels-Capital Region.
The region field should not be used for the country

2021-11-09 20:10 UTC, luc-demeyer commented
@rousseldenis 
Great contribution, thanks a lot.
Based upon code review: only one small remark: correct tests for regions.
I think we should merge this ASAP.

@alexis-via 
Ths PR looks great to me but I think you should test your DES declaration since a lot code has been moved by Denis from the product declaration to the intrastat common class, hence you can drop a lot of code from both your DEB and DES declaration but it seems recommended to to check if nothing breaks and eventually fix in the DES before merging this PR.

2021-11-10 15:00 UTC, rousseldenis commented on intrastat_product/tests/common.py
> +        if vals is not None:
Here are only for tests purpose. But if you'd prefer I will create a real region instead

2021-11-10 15:44 UTC, luc-demeyer commented on intrastat_product/tests/common.py
> +        if vals is not None:
I prefer using real regions: less confusing and better coverage.

2021-11-11 12:26 UTC, rousseldenis commented
@luc-demeyer Done

2021-11-11 16:35 UTC, luc-demeyer approved these changes

2021-11-18 11:05 UTC, rousseldenis commented
@luc-demeyer Can we merge this as I will need to add a breaking change in a new PR ?

2021-11-18 13:16 UTC, luc-demeyer commented
@alexis-via 
please give green ligth to merge this one.

2021-12-12 23:07 UTC, alexis-via commented
I would have preferred to drop the class intrastat.common altogether. The synergies bought by intrastat.common were pretty low. Droppping intrastat.common would have simplified the code.

Unfortunately, this PR doesn't tackle the 2 priorities:
- migration of hs_code_id on product.template/product.category to company_dependent=False
- rewrite the warnings/log system of intrastat.product.declaration to avoid have the same warning multiple times (where the same product with missing data is present in several invoice lines for example)

2021-12-13 21:22 UTC, luc-demeyer commented
@alexis-via 

This PR adds a nice set of unit tests, hence a great improvement.

Also for me dropping intrastat_common makes sense (the belgian 'services' declaration doesn't depend on this one).
This can be done in 15.0 migration (or a seperate PR but will break your french DES declaration).

Migration of hs_code_id on product.template/product.category to company_dependent=False : that issue will soon be solved by your https://github.com/OCA/intrastat-extrastat/pull/156

Rewrite the warnings/log system: I don't have too many complaints about this one in my customer base, hence low prio for me, but improving this is imho also not a showstopper for merging this PR.

2021-12-14 23:05 UTC, alexis-via commented
Sorry if my message was not very positive. The great thing with this PR is the addition of test.
What do you think about my proposal to drop the class intrastat.common ? If you agree on that, I can work on a PR to update this PR.

2021-12-15 06:14 UTC, rousseldenis commented
> Sorry if my message was not very positive. The great thing with this PR is the addition of test. What do you think about my proposal to drop the class intrastat.common ? If you agree on that, I can work on a PR to update this PR.

This PR was not aimed to enhance code but to introduce tests.

My opinion is that we can merge this fast and then doing improvements. To avoid a too great PR, which is difficult to review

2021-12-15 06:20 UTC, rousseldenis commented
> I would have preferred to drop the class intrastat.common altogether. The synergies bought by intrastat.common were pretty low. Droppping intrastat.common would have simplified the code.
> 
> Unfortunately, this PR doesn't tackle the 2 priorities:
> 
> * migration of hs_code_id on product.template/product.category to company_dependent=False
> * rewrite the warnings/log system of intrastat.product.declaration to avoid have the same warning multiple times (where the same product with missing data is present in several invoice lines for example)

Indeed, this PR highlighted the fact that common class hasn't real added value.

I would tend to say, let's do two new PR's (based on this - for tests) with one change at a time.

2021-12-15 07:17 UTC, luc-demeyer commented
I am in favour of proposal from @rousseldenis : merge this one and do the other changes via add-on PRs.

2021-12-15 10:20 UTC, alexis-via commented
Don't worry, I'll do it. I'm the most impacted by this change because this PR breaks l10n_fr_intrastat_service, so I have to invest time anyway to repair the breakage.

2021-12-15 10:43 UTC, alexis-via commented
My PR will also fix the fact that the file "account_fiscal_position_template.py " is not imported intrastat_base.

2021-12-15 14:34 UTC, alexis-via commented
My PR to update and fix PR: https://github.com/acsone/intrastat-extrastat/pull/1
The main change is the removal of intrastat.common.

2021-12-15 15:41 UTC, alexis-via commented
I prefer to do all the work in a single PR and not in several PRs, because of the impact on the modules of OCA/l10n-france. It would be too time consuming to make several PRs and, every time, update the code and do the coordination in localization modules.

2021-12-20 15:46 UTC, alexis-via approved these changes

2021-12-26 20:05 UTC, luc-demeyer commented
/ocabot merge minor

2021-12-26 20:13 UTC, merged