region attrs invisible
OCA/intrastat-extrastat pull request #16
Opened 2017-07-25 16:10 UTC by luc-demeyer

some localisation modules (e.g. Belgium) require the region field.
Other localisations also require the region concept for the intrastat declaration but this requirement is fulfilled via other means, e.g.
- France : departments
- Spain : states

This creates a confusing User Interfaces with region, department and state fields on several objects when running in a multi-company setup with multiple intrastat localisations.

This PR solves this by implementing the display/non-display logic of the country field to the 'intrastat_product' module whereby a list of country codes in the "attrs" attribute determines the visibility.

2017-08-26 12:57 UTC, pedrobaeza commented
Please change version number

2017-08-28 09:07 UTC, pedrobaeza requested changes

2017-08-28 09:07 UTC, pedrobaeza commented on intrastat_product/models/account_invoice.py
> +        related='company_id.country_id.code')
Please add `readonly=True` for avoiding undesired write back.

2017-08-28 09:07 UTC, pedrobaeza commented on intrastat_product/models/res_company.py
> +        related='country_id.code')
`readonly=True`

2017-08-28 09:07 UTC, pedrobaeza commented on intrastat_product/models/stock_warehouse.py
> +        related='company_id.country_id.code')
`readonly=True`

2017-08-28 14:19 UTC, pedrobaeza approved these changes

2017-08-28 22:38 UTC, alexis-via requested changes

2017-08-28 22:38 UTC, alexis-via commented on intrastat_product/views/account_invoice.xml
> +                 attrs="{'invisible': [('src_dest_country_code', 'not in', ['BE'])]}"/>
I don't agree on that one.
I am a belgian company and I ship from Belgium to France. On the customer invoice:
src_dest_country_code = FR
src_dest_region_id = the Belgian region from where the goods are shipped
-> so it should not be invisible here !

2017-08-28 22:38 UTC, alexis-via commented on intrastat_product/views/account_invoice.xml
>          </xpath>
I don't agree either, for the same reason.

2017-08-29 16:37 UTC, luc-demeyer commented
@alexis-via 
I understand the confusion. 
Technically the PR is ok since src_dest_country_code is related to the company country but on the invoice the name could suggest that it is related to the src_dest_country_id field.
I'll adapt the PR with  a field name that is less confusing.

2017-08-29 20:59 UTC, alexis-via approved these changes

2017-08-29 20:59 UTC, merged