[10.0] add xls export & generic declaration
OCA/intrastat-extrastat pull request #41
Opened 2018-08-10 10:52 UTC by luc-demeyer

This PR adds a generic (hence non-country specific)  declaration to the OCA intrastat suite.
The purpose of this module is to facilitate Intrastat declarations for the European countries without an OCA Intrastat localisation module. 
The generic declaration comes with an excel export of both the computation lines and the declaration lines and hence can be used to send to an external accountant or load the data (after analysis & conversion) into a local accounting package which than submits the country specific declaration.

I have added the Excel export into the  'intrastat_product' module since this is also useful for analysis of Intrastat declaration in countries with an existing localisation module (e.g. France & Belgium).
The export comes with an excel template that can be modified via inherit in the localisation to add extra field (e.g. the regions in Belgium, departments in France, states in Spain, ... ).

This PR depends upon https://github.com/OCA/reporting-engine/pull/204, hence I would appreciate the reviewers of this PR to also have a look this prereq PR.

2018-08-17 13:43 UTC, pankk requested changes
Also did a functional test using demo data; created an invoice using products with H.S. codes; 'Generate lines from invoices'; 'Generate declaration lines', and exported the two XLSX files successfully.

2018-08-17 13:43 UTC, pankk commented on intrastat_product_generic/README.rst
> +This is usefull to cover countries for which there is no localization module.
usefull: spelling

2018-08-17 13:43 UTC, pankk commented on intrastat_product/views/intrastat_product_declaration.xml
> +                <field name="year"/>
widget="char" to avoid misplaced separators

2018-08-17 13:43 UTC, pankk commented on intrastat_product/report/intrastat_product_report_xls.py
> +# from odoo.exceptions import UserError
remove

2018-08-17 13:43 UTC, pankk commented on intrastat_product/report/intrastat_product_report_xls.py
> +        ws.set_portrait()
A landscape worksheet would be more readable, particularly for the computation lines spreadsheet.

2018-08-17 16:26 UTC, luc-demeyer commented
@pankk 
Thanks for your review.
I have included all your suggestions into the PR.

2018-08-20 06:57 UTC, pankk commented
@luc-demeyer Thanks for doing this PR in the first place. codecov and runbot are still red. I don't know why runbot is red, perhaps a dependency issue?

2018-10-02 14:42 UTC, alexis-via approved these changes

2018-10-02 14:43 UTC, merged