[MIG] 9.0 intrastat_base
OCA/intrastat-extrastat pull request #8
Opened 2016-12-02 16:51 UTC by thomaspaulb

Migrated and added tests.

2016-12-06 16:24 UTC, hbrunn requested changes
only a few nags

2016-12-06 16:24 UTC, hbrunn commented on intrastat_base/data/country_data.xml
> +<data noupdate="1">
better leave `<odoo>`, that's the new standard in 9 too

2016-12-06 16:24 UTC, hbrunn commented on intrastat_base/tests/__init__.py
> +##############################################################################
use short headers, and update your licence template ;-)

2016-12-06 16:24 UTC, hbrunn commented on intrastat_base/tests/__init__.py
> +# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
modelines are scorned upon by now

2016-12-06 16:24 UTC, hbrunn commented on intrastat_base/tests/intrastat_base_tests.py
> +# -*- coding: utf-8 -*-
this is valuable code too and deserves your license

2016-12-06 16:24 UTC, hbrunn commented on intrastat_base/tests/intrastat_base_tests.py
> +
remove empty lines

2016-12-06 16:40 UTC, thomaspaulb commented on intrastat_base/tests/intrastat_base_tests.py
> +# © 2016 Sunflower IT (http://sunflowerweb.nl).
This file was purely added by me, but I don't know what is the policy for that?

2016-12-06 17:29 UTC, hbrunn commented on intrastat_base/tests/intrastat_base_tests.py
> +# © 2016 Sunflower IT (http://sunflowerweb.nl).
the policy is if you add something, it's your copyright

2017-01-11 14:57 UTC, hbrunn approved these changes

2017-01-11 23:08 UTC, alexis-via approved these changes

2017-01-11 23:08 UTC, merged